apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poolbeg.fullname" . }}-config
  labels:
    {{- include "poolbeg.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}
