{{- if and .Values.secrets (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "meddler.fullname" . }}-secrets
  labels:
    {{- include "meddler.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
