{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "meddler.fullname" . }}
  labels:
    {{- include "meddler.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "meddler.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.config.server.metrics.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
